### PR TITLE
Role-based column visibility and asynchronous fetching of roles

### LINKED ISSUE #25: Add "Supplier" and "Customer" Columns to the Table
## Description
Modify the table to add "Supplier" and "Customer" columns. Ensure that the table can accommodate situations where a Business Partner is both a customer and a supplier.

## Product Name
[vas-country-risk](https://github.com/eclipse-tractusx/vas-country-risk)

## Tasks
- [x] Add "Supplier" and "Customer" columns to the table.
- [x] Ensure the table can handle Business Partners that are both a supplier and a customer.

### LINKED ISSUE #26: Add New Roles for Business Partner Access
## Description
Create and implement three new roles that determine access to Business Partner information. These roles are: access to both (suppliers and customers), access to suppliers only, access to customers only.

## Product Name
[vas-country-risk](https://github.com/eclipse-tractusx/vas-country-risk)

## Tasks
- [x] Define and implement three new roles.
- [x] Set access rules according to the role definitions.

### LINKED ISSUE #27: Conduct Tests and Upgrade Application Versions
## Description
Conduct tests to ensure that the new columns, roles, and API mapping are working as expected. In addition, upgrade the versions of the applications being used and maintain a change log documenting the upgrades and associated changes.

## Product Name
[vas-country-risk](https://github.com/eclipse-tractusx/vas-country-risk)

## Tasks
- [x] Test the new columns, roles, and API mapping to ensure they work as expected.
- [x] Upgrade application versions.
- [x] Maintain a change log documenting the application upgrades and associated changes.

### PR DESCRIPTION
**Pull request by fabiodmota**
## Description

This PR introduces new features and fixes. It adds role-based column visibility in tables where 'Supplier' and 'Customer' columns are now hidden or shown based on user roles. It also introduces asynchronous fetching of roles to ensure they are available before rendering the table. A fix has been implemented for an issue where roles could be undefined, causing an error when calling the includes method. Additionally, the client id for the country risk app registered on the portal has been changed.

Fixes #25  
Fixes #26 
Fixes #27 

## Pre-review checks

- [x] DEPENDENCIES are up to date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] Copyright and license header are present on all affected files

### Additional information

- To request a review, check out [who's involved](https://projects.eclipse.org/projects/automotive.tractusx/who) to see a list of contributors and committers
- Use the [mailing list](https://accounts.eclipse.org/mailing-list/tractusx-dev) if you are unsure, who to contact, or if want to engage in a general discussion
- Check out our guide on [how to contribute](https://eclipse-tractusx.github.io/docs/oss/how-to-contribute)
- Check out our [Release Guidelines](https://eclipse-tractusx.github.io/docs/release)
- Check out the [Eclipse Foundation contribution guidelines](https://www.eclipse.org/projects/handbook/#contributing)

### CODE REVIEW

**Review by SebastianBezold — APPROVED** [review]
LGTM. FYI: I'll fix the PR description. I'll remove the frontmatter part at the beginning, since it's only duplication of the actual title and fix the issue number links. The URLs are fine, but you would usually just have the issue number as reference

**Comment by SebastianBezold** [comment]
Before merging, a content review of someone who can check the JavaScript changes would be appreciated

**Comment by alexsilva-CGI** [comment]
Tested frontend application and it works good. Code looks good to. Ok from me

**Comment by SebastianBezold** [comment]
> Tested frontend application and it works good. Code looks good to. Ok from me

Thanks for testing @alexsilva-CGI! Should we add you as Tractus-X contributor? Then you can use the "approve" function and it would show up in the "Reviewers" section on the top right of the issue

**Pull request merged**
