### PR TITLE
Feat - PDF World Map

### PR DESCRIPTION
**Pull request by alexsilva-CGI**
---
Title: PDF World Map
---

## Description

This PR adds the ability for the user to export some information together with the world map (Ranges, Ratings, Date, Gate) in 
a PDF file instead of an PNG.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up to date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] Copyright and license header are present on all affected files

### Additional information

- To request a review, check out [who's involved](https://projects.eclipse.org/projects/automotive.tractusx/who) to see a list of contributors and committers
- Use the [mailing list](https://accounts.eclipse.org/mailing-list/tractusx-dev) if you are unsure, who to contact, or if want to engage in a general discussion
- Check out our guide on [how to contribute](https://eclipse-tractusx.github.io/docs/oss/how-to-contribute)
- Check out our [Release Guidelines](https://eclipse-tractusx.github.io/docs/release)
- Check out the [Eclipse Foundation contribution guidelines](https://www.eclipse.org/projects/handbook/#contributing)

### CODE REVIEW

**Comment by alexsilva-CGI** [comment]
Additions and deletions seem a lot, but are mainly from Package-lock.json file.  Some dependencies need some check also: 
image

**Comment by SebastianBezold** [comment]
Hi @alexsilva-CGI,
just ran the automatic IP issue creation. Following issues where created:

- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9432
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9433
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9434
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9435

There was an API rate limit exception though, that I did never experience before. I'll look into it and see if all needed issues have been created. I already committed the updated `DEPENDENCIES`

**Comment by SebastianBezold** [comment]
Rate limit issue gone. Two additional tickets created:

- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9437
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9438

**Comment by fabiodmota** [comment]
Hello @SebastianBezold thank for all the IP Checks created, i think all of them is closed and no need to update again the Dependecie file

**Comment by SebastianBezold** [comment]
Hi @fabiodmota,
thanks for tracking the changes. The vast majority of changes in this PR comes from updated dependencies in the `package-lock.json` file. So no need for further project content review in my opinion

**Pull request merged**
