### PR TITLE
docs(frontend): Change docs from png to mermaid references

### PR DESCRIPTION
**Pull request by fabiodmota**
## Description
Changing Database diagrams, sequence diagrams and component diagrams to mermaid formats 

fixes https://github.com/eclipse-tractusx/vas-country-risk/issues/91

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by FaGru3n — APPROVED** [review]
LGTM but some diagram files are still in .png format so changed the PR to updates the issues

**Comment by fabiodmota** [comment]
Hi @FaGru3n , i used your Database diagram thanks for that
https://github.com/catenax-ng/tx-vas-country-risk-frontend/blob/docs/convert_png_to_mermaid/docs/Arc42-Documentation.md#architecture-decisions
and finished all the diagrams that i found, if nothing else we can conclude the TRG and close the issue

**Comment by FaGru3n** [comment]
> Hi @FaGru3n , i used your Database diagram thanks for that https://github.com/catenax-ng/tx-vas-country-risk-frontend/blob/docs/convert_png_to_mermaid/docs/Arc42-Documentation.md#architecture-decisions and finished all the diagrams that i found, if nothing else we can conclude the TRG and close the issue

i guess a half way track for the pictures that have to be editable.

Found also some sequence diagramms that could be easily adopted with mermaid

for example and all other "DashBoardRessource_xxxxx" could also be modified.
https://github.com/eclipse-tractusx/vas-country-risk/blob/main/docs/Images/DashBoardResource_getAllDashBoardTable.jpg

**Comment by fabiodmota** [comment]
> > Hi @FaGru3n , i used your Database diagram thanks for that https://github.com/catenax-ng/tx-vas-country-risk-frontend/blob/docs/convert_png_to_mermaid/docs/Arc42-Documentation.md#architecture-decisions and finished all the diagrams that i found, if nothing else we can conclude the TRG and close the issue
> 
> i guess a half way track for the pictures that have to be editable.
> 
> Found also some sequence diagramms that could be easily adopted with mermaid
> 
> for example and all other "DashBoardRessource_xxxxx" could also be modified. https://github.com/eclipse-tractusx/vas-country-risk/blob/main/docs/Images/DashBoardResource_getAllDashBoardTable.jpg

Already switched all sequence image to mermaid sequence diagrams to complete the TRG checks !

**Pull request merged**
